### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by felifri** [BigML-CS-UCLA/SpuCo#19]
`pip install spuco` doesn't work on different machines with different python and pip versions.

**Comment by sjoshi804** [comment]
Hi, can you elaborate? Which version of python is this not working with?

**Comment by felifri** [comment]
I tried all python 3.7 to 3.10. However, I could fix it by updating python to 3.11. Might be worth mentioning

**Comment by sjoshi804** [comment]
Thanks for letting us know! 

Can you share a repro of your error on Python 3.10? 

We have specified in the pyproject.toml that Python >= 3.10 is required and I'm able to install spuco correctly with python=3.10.

**Comment by felifri** [comment]
I probably didn't check 3.10 carefully, it works now. Before, I got the errors:

```
ERROR: Could not find a version that satisfies the requirement spuco (from versions: none)
ERROR: No matching distribution found for spuco
```

**Comment by sjoshi804** [comment]
Yes, we specify python >=3.10 as a requirement.

Thanks for checking.
