### ISSUE TITLE
Error in SpareInference: Cluster.__init__() got an unexpected keyword argument 'random_seed'

### ISSUE THREAD

**Issue by lllllyh01** [BigML-CS-UCLA/SpuCo#23]
Hi, I met an error when running SpareInference in group_inference: `Cluster.__init__() got an unexpected keyword argument 'random_seed'`
I think it may because of the incompatible between the initialize functions of SpareInterface and its father class.  SpareInference takes a `random_seed` parameter when calling __init__ function of its father Cluster:
<img width="626" alt="spare" src="https://github.com/BigML-CS-UCLA/SpuCo/assets/62642577/1dcc71bc-4060-4089-9380-e3c2e02992e2">
But the __init__ in Cluster doesn't have this parameter:
<img width="365" alt="cluster" src="https://github.com/BigML-CS-UCLA/SpuCo/assets/62642577/34a4fd13-1714-446e-a167-78a62bd53434">

**Comment by sjoshi804** [comment]
Hi, acknowledged, we will look into fixing this soon. You're also welcome and encouraged to open a PR to fix this!

**Comment by WeizhenWang-1210** [comment]
Just wanna follow up: what exactly does the Spare_inference.infer_groups() return? I see the return type is a tuple of two, where the first element of the tuple is a dictionary with keys being (class_id, cluster_id) and values being the index of Z. However, what's the meaning of the second element of the tuple?

**Comment by sjoshi804** [comment]
Fixed. 

Cluster id is the inferred spurious feature id.
